# Generated by Django 3.2.3 on 2021-05-25 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='residential_address',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
