# Generated by Django 3.2.3 on 2021-05-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_alter_customer_residential_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
