# Generated by Django 3.2.3 on 2021-05-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0003_auto_20210525_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
