# Generated by Django 3.2.3 on 2021-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0006_event_eventcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PostCategory',
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(to='net.EventCategory'),
        ),
    ]
