# Generated by Django 3.2.3 on 2021-06-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0009_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
