# Generated by Django 3.2.3 on 2022-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0012_auto_20220117_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='eventdefault.jpg', null=True, upload_to='event_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='postdefault.jpg', null=True, upload_to='post_pics'),
        ),
    ]
