# Generated by Django 3.2.3 on 2022-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0013_auto_20220203_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='eventdefault.jpg', null=True, upload_to='event_pics'),
        ),
    ]
