# Generated by Django 3.2.3 on 2022-02-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0014_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='eventdefault.jpg', upload_to='event_pics'),
        ),
    ]
