# Generated by Django 3.2.3 on 2022-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0016_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
