# Generated by Django 3.2.3 on 2022-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0017_post_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
