# Generated by Django 3.2.3 on 2022-02-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0018_auto_20220203_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_posted',
            new_name='date_sent',
        ),
    ]
